---
name: Delete Old Workflow Runs
"on":
  schedule:
  - cron: "0 10 15,28 * *"
  workflow_dispatch:
    inputs:
      retain_days:
        description: Number of days to keep workflow runs (0 to include today)
        required: false
        default: "1"
      keep_minimum_runs:
        description: Minimum number of workflow runs to keep
        required: false
        default: "2"
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
    - name: Delete old workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        repository: "${{ github.repository }}"
        retain_days: "${{ github.event.inputs.retain_days || '1' }}"
        keep_minimum_runs: "${{ github.event.inputs.keep_minimum_runs || '2' }}"
